name: Job Dependencies Demo

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: echo "Job 1 is running"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Job 2
        run: echo "Job 2 is running"

  job3:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - name: Job 3
        run: echo "Job 3 is running after Job 1 and Job 2"

  job4:
    needs: job3
    runs-on: ubuntu-latest
    steps:
      - name: Job 4
        run: echo "Job 4 is running after Job 3"
