name: Secrets and Vars

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Use username
        run: |
          echo "User found!"
          echo "${USER_NAME}"
        env:
          USER_NAME: ${{ vars.USER_NAME }}

      - name: Use secret
        run: |
          echo "Password is set!"
          echo "$PASSWORD"
          echo "Length: ${#PASSWORD}"
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
